version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
#    command: sleep infinity
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - ${APP_PORT}:80
    environment:
      - APP_NAME=tv-notification-service
      - APP_ENV=local
      - APP_KEY=base64:0xPWU7myp18Jd4RHZ115ke3iMG8UWbAPk5d5tfEdMoo=
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000
      - LOG_CHANNEL=stderr
      - LOG_DEPRECATIONS_CHANNEL=null
      - LOG_LEVEL=debug
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=app
      - DB_USERNAME=user
      - DB_PASSWORD=pass
      - BROADCAST_DRIVER=log
      - CACHE_DRIVER=file
      - FILESYSTEM_DISK=local
      - QUEUE_CONNECTION=sync
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120
      - MEMCACHED_HOST=127.0.0.1
      - L5_SWAGGER_GENERATE_ALWAYS=true
